config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index", as: :index

  get "tasks/new", to: "tasks#new", as: :new
  post "tasks", to: "tasks#create", as: :tasks

  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update", as: :update

  get "tasks/:id", to: "tasks#show", as: :show

  delete "tasks/:id", to: "tasks#destroy", as: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to index_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    if params["task"]["completed"].to_s == 'true'
      params["task"]["completed"] = true
    elsif params["task"]["completed"].to_s == 'false'
      params["task"]["completed"] = false
    end
    @task = Task.find(params[:id])
    @task.update({completed: params["task"]["completed"]})
    @task.update(task_params)
    @task.save!
    redirect_to show_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to index_path
  end

  private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/destroy.html.erb
destroy.html.erb

app/views/tasks/edit.html.erb
<h2>Let's update <%= @task.title.upcase %> :)</h2>

<%= form_for(@task, url: update_path(@task), method: "patch") do %>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Title:</label>
  <input type="text" name="task[title]" id="tilte" value="<%= @task.title %>">

  <label for="details">Details: </label>
  <input type="text" name="task[details]" id="details" value="<%= @task.details %>">

  <label for="completed">Completed: </label>
  <input type="boolean" name="task[completed]" id="completed" value="<%= @task.completed %>">

  <input type="submit">
<% end %>

app/views/tasks/index.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

<ul>
  <% @tasks.each do |task| %>
    <li>
      <h2>
          <% if task.completed == true  %>
          <i class="fas fa-check-circle"></i>
          <% end  %>
          <% if task.completed == false  %>
          <i class="fas fa-circle"></i>
          <% end  %>
        <%= link_to task.title, show_path(task.id) %>
        <%= link_to "Delete", destroy_path(task.id),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
      </h2>
    </li>
  <% end  %>
</ul>

<%= link_to "Add a Task", new_path %>

app/views/tasks/new.html.erb
<h2>Let's add a new task :)</h2>



<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

<h1>
  <%= @task.title %>
</h1>


<h2>
  <%= @task.details %>
</h2>

<h3>
  <% if @task.completed == true  %>
  <i class="fas fa-check-circle"></i>
    <%= "Task has been completed!" %>
  <% end  %>
  <% if @task.completed == false  %>
  <i class="fas fa-circle"></i>
    <%= "Task has not been completed!" %>
  <% end  %>
</h3>

<%= link_to "Return to tasks", index_path %>


<%= link_to "Update task", edit_path(@task.id) %>